// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyhcvnzjovzlwsybpydn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5aGN2bnpqb3Z6bHdzeWJweWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMjE2NDQsImV4cCI6MjA4ODU5NzY0NH0.3PCUD6hS5_6BWCafoPR9GBnitwPA4AOjs1Yaz-VYHQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});